{
  appDir: C:\Users\Max\Desktop\Ashen Macros 2.0,
  appExecName: rotten.py,
  appIdentifier: shrink.py,
  appRepo: https://github.com/koetsmax/Ashen-Macros-2.0,
  backupOn: false,
  createLaunchScriptOn: false,
}
